# starship config

add_newline = true

[character]
#âžœ
success_symbol = "[|>](bold yellow)"
error_symbol = "[âœ–](bold red) "

[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "-"
style = "bold dimmed green"
disabled = false

#[time]
#time_format = "%T"
#format = "ðŸš€ $time($style) "
#style = "bright-white"
#disabled = false

[username]
style_user = "bold dimmed blue"
format = "[$user]($style)@"
show_always = true
