# starship config

add_newline = true

[character]
#➜λΔ✖
success_symbol = "[\\$](white)"
error_symbol = "[X](bold red) "

[directory]
truncation_length = 4
style = "italic blue"
format = "in [$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "italic purple"
format = "[$branch]($style) "
